import type { NextPage } from "next";
import Head from "next/head";

const catalogo: NextPage = () => {
    return (
        <div>
            Hola Catalogo
            {/* <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
        </div>
    );
};

export default catalogo;
